image: alpine:3

pages:
  script:
    - apk add brotli gzip
    - find public -type f -regex '.*\.\(html\|js\|css\|svg\|json\)$' -print0 > compressable.txt
    - xargs -0 -a compressable.txt gzip --best --force --keep
    - xargs -0 -a compressable.txt brotli 
  artifacts:
    paths:
    - public
  only:
  - master
