image: alpine:3

pages:
  script:
    - apk add brotli gzip
    - find public -regex '.*\.\(html\|js\|css\|svg\)$' > compressable.txt
    - xargs -a compressable.txt gzip --best --force --keep
    - xargs -a compressable.txt brotli 
  artifacts:
    paths:
    - public
  only:
  - master
